export { ContactsArgsSchema, type ContactsArgs } from './contacts.schema.js';
export { NotesArgsSchema, type NotesArgs } from './notes.schema.js';
export { MessagesArgsSchema, type MessagesArgs } from './messages.schema.js';
export { MailArgsSchema, type MailArgs } from './mail.schema.js';
export { RemindersArgsSchema, type RemindersArgs } from './reminders.schema.js';
export { CalendarArgsSchema, type CalendarArgs } from './calendar.schema.js';
export { MapsArgsSchema, type MapsArgs } from './maps.schema.js';
export { SafariArgsSchema, type SafariArgs } from './safari.schema.js';
export { PhotosArgsSchema, type PhotosArgs } from './photos.schema.js';
